# Generated by Django 3.1.7 on 2021-02-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sobrenome', models.CharField(max_length=200)),
                ('cpf', models.IntegerField()),
                ('rg', models.IntegerField()),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('endereco', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=200)),
                ('complemento', models.CharField(max_length=200)),
            ],
        ),
    ]
